{
	"game": [{
			"gno": 1,
			"gname": "六 合 彩",
			"ggno": 1,
			"rule": "YYYYNNN"
		}, {
			"gno": 2,
			"gname": "福彩3D",
			"ggno": 2,
			"rule": "YYYYNNN"
		}, {
			"gno": 3,
			"gname": "体彩P3",
			"ggno": 2,
			"rule": "YYNNN"
		}, {
			"gno": 4,
			"gname": "上海时时乐",
			"ggno": 2,
			"rule": "YYYYMMDD-NN"
		}, {
			"gno": 5,
			"gname": "黑龙江时时彩",
			"ggno": 3,
			"rule": "NNNNNNNN"
		}, {
			"gno": 6,
			"gname": "重庆时时彩",
			"ggno": 3,
			"rule": "YYYYMMDD-NNN"
		}, {
			"gno": 7,
			"gname": "江西时时彩",
			"ggno": 3,
			"rule": "YYYYMMDD-NNN"
		}, {
			"gno": 8,
			"gname": "广东快乐十分",
			"ggno": 4,
			"rule": "YYYYMMDD-NN"
		}, {
			"gno": 9,
			"gname": "广西快乐十分",
			"ggno": 5,
			"rule": "YYYYAAA-NN"
		}, {
			"gno": 10,
			"gname": "新疆时时彩",
			"ggno": 3,
			"rule": "YYYYMMDD-NN"
		}, {
			"gno": 11,
			"gname": "北京赛车",
			"ggno": 6,
			"rule": "NNNNNN"
		}, {
			"gno": 12,
			"gname": "江苏快3",
			"ggno": 7,
			"rule": "YYYYMMDDNNN"
		}, {
			"gno": 13,
			"gname": "北京快乐8",
			"ggno": 8,
			"rule": "NNNNNN"
		}, {
			"gno": 14,
			"gname": "天津时时彩",
			"ggno": 3,
			"rule": "YYYYMMDDNNN"
		}, {
			"gno": 15,
			"gname": "山东11选五",
			"ggno": 9,
			"rule": "YYYYMMDDNN"
		},
		{
			"gno": 17,
			"gname": "江西11选五",
			"ggno": 9,
			"rule": "YYYYMMDDNN"
		}, {
			"gno": 18,
			"gname": "广东11选五",
			"ggno": 9,
			"rule": "YYYYMMDDNN"
		}, {
			"gno": 19,
			"gname": "安徽快三",
			"ggno": 7,
			"rule": "YYYYMMDDNNN"
		}, {
			"gno": 20,
			"gname": "幸运农场",
			"ggno": 4,
			"rule": "YYYYMMDD-NN"
		}, {
			"gno": 21,
			"gname": "幸运飞艇",
			"ggno": 6,
			"rule": "YYYYMMDDNNN"
		}, {
			"gno": 22,
			"gname": "极速赛车",
			"ggno": 6,
			"rule": "NNNNNNNN"
		}, {
			"gno": 23,
			"gname": "极速时时彩",
			"ggno": 3,
			"rule": "NNNNNNNN"
		}, {
			"gno": 24,
			"gname": "体彩P5",
			"ggno": 3,
			"rule": "YYNNN"
		}, {
			"gno": 25,
			"gname": "七星彩",
			"ggno": 11,
			"rule": "YYNNN"
		}, {
			"gno": 26,
			"gname": "自营赛车",
			"ggno": 6,
			"rule": "YYYYMMDDNNN"
		}, {
			"gno": 27,
			"gname": "自营时时彩",
			"ggno": 3,
			"rule": "YYYYMMDDNNN"
		}
	],
	"oddsgroup": [{
			"oddsgno": 201,
			"oddsgname": "正码"
		}, {
			"oddsgno": 202,
			"oddsgname": "一字不定位(前三)"
		}, {
			"oddsgno": 203,
			"oddsgname": "一字不定位(中三)"
		}, {
			"oddsgno": 204,
			"oddsgname": "一字不定位(后三)"
		}, {
			"oddsgno": 205,
			"oddsgname": "第一球"
		}, {
			"oddsgno": 206,
			"oddsgname": "第二球"
		}, {
			"oddsgno": 207,
			"oddsgname": "第三球"
		}, {
			"oddsgno": 208,
			"oddsgname": "第四球"
		}, {
			"oddsgno": 209,
			"oddsgname": "第五球"
		}, {
			"oddsgno": 210,
			"oddsgname": "第一球大小"
		}, {
			"oddsgno": 211,
			"oddsgname": "第二球大小"
		}, {
			"oddsgno": 212,
			"oddsgname": "第三球大小"
		}, {
			"oddsgno": 213,
			"oddsgname": "第四球大小"
		}, {
			"oddsgno": 214,
			"oddsgname": "第五球大小"
		},
		{
			"oddsgno": 215,
			"oddsgname": "第一球单双"
		}, {
			"oddsgno": 216,
			"oddsgname": "第二球单双"
		}, {
			"oddsgno": 217,
			"oddsgname": "第三球单双"
		}, {
			"oddsgno": 218,
			"oddsgname": "第四球单双"
		}, {
			"oddsgno": 219,
			"oddsgname": "第五球单双"
		}, {
			"oddsgno": 220,
			"oddsgname": "万质合"
		}, {
			"oddsgno": 221,
			"oddsgname": "千质合"
		}, {
			"oddsgno": 222,
			"oddsgname": "百质合"
		}, {
			"oddsgno": 223,
			"oddsgname": "拾质合"
		},
		{
			"oddsgno": 224,
			"oddsgname": "个质合"
		}, {
			"oddsgno": 225,
			"oddsgname": "二字不定位(前三)"
		}, {
			"oddsgno": 226,
			"oddsgname": "二字不定位(中三)"
		}, {
			"oddsgno": 227,
			"oddsgname": "二字不定位(后三)"
		}, {
			"oddsgno": 228,
			"oddsgname": "百拾定位(前三)"
		}, {
			"oddsgno": 229,
			"oddsgname": "百拾定位(中三)"
		}, {
			"oddsgno": 230,
			"oddsgname": "百拾定位(后三)"
		}, {
			"oddsgno": 231,
			"oddsgname": "百个定位(前三)"
		},
		{
			"oddsgno": 232,
			"oddsgname": "百个定位(中三)"
		}, {
			"oddsgno": 233,
			"oddsgname": "百个定位(后三)"
		}, {
			"oddsgno": 234,
			"oddsgname": "拾个定位(前三)"
		}, {
			"oddsgno": 235,
			"oddsgname": "拾个定位(中三)"
		}, {
			"oddsgno": 236,
			"oddsgname": "拾个定位(后三)"
		}, {
			"oddsgno": 237,
			"oddsgname": "百拾和数单双(前三)"
		}, {
			"oddsgno": 238,
			"oddsgname": "百拾和数单双(中三)"
		},
		{
			"oddsgno": 239,
			"oddsgname": "百拾和数单双(后三)"
		}, {
			"oddsgno": 240,
			"oddsgname": "百个和数单双(前三)"
		}, {
			"oddsgno": 241,
			"oddsgname": "百个和数单双(中三)"
		}, {
			"oddsgno": 242,
			"oddsgname": "百个和数单双(后三)"
		}, {
			"oddsgno": 243,
			"oddsgname": "拾个和数单双(前三)"
		}, {
			"oddsgno": 244,
			"oddsgname": "拾个和数单双(中三)"
		}, {
			"oddsgno": 245,
			"oddsgname": "拾个和数单双(后三)"
		}, {
			"oddsgno": 246,
			"oddsgname": "三字不定位(前三)"
		}, {
			"oddsgno": 247,
			"oddsgname": "三字不定位(中三)"
		}, {
			"oddsgno": 248,
			"oddsgname": "三字不定位(后三)"
		}, {
			"oddsgno": 249,
			"oddsgname": "百拾个定位(前三)"
		}, {
			"oddsgno": 250,
			"oddsgname": "百拾个定位(中三)"
		}, {
			"oddsgno": 251,
			"oddsgname": "百拾个定位(后三)"
		},
		{
			"oddsgno": 252,
			"oddsgname": "百拾个和数大小(前三)"
		}, {
			"oddsgno": 253,
			"oddsgname": "百拾个和数大小(中三)"
		}, {
			"oddsgno": 254,
			"oddsgname": "百拾个和数大小(后三)"
		}, {
			"oddsgno": 255,
			"oddsgname": "百拾个和数单双(前三)"
		}, {
			"oddsgno": 256,
			"oddsgname": "百拾个和数单双(中三)"
		}, {
			"oddsgno": 257,
			"oddsgname": "百拾个和数单双(后三)"
		},
		{
			"oddsgno": 258,
			"oddsgname": "组选三-5(前三)"
		}, {
			"oddsgno": 259,
			"oddsgname": "组选三-5(中三)"
		}, {
			"oddsgno": 260,
			"oddsgname": "组选三-5(后三)"
		}, {
			"oddsgno": 261,
			"oddsgname": "组选三-6(前三)"
		}, {
			"oddsgno": 262,
			"oddsgname": "组选三-6(中三)"
		}, {
			"oddsgno": 263,
			"oddsgname": "组选三-6(后三)"
		}, {
			"oddsgno": 264,
			"oddsgname": "组选三-7(前三)"
		}, {
			"oddsgno": 265,
			"oddsgname": "组选三-7(中三)"
		},
		{
			"oddsgno": 266,
			"oddsgname": "组选三-7(后三)"
		}, {
			"oddsgno": 267,
			"oddsgname": "组选三-8(前三)"
		}, {
			"oddsgno": 268,
			"oddsgname": "组选三-8(中三)"
		}, {
			"oddsgno": 269,
			"oddsgname": "组选三-8(后三)"
		}, {
			"oddsgno": 270,
			"oddsgname": "组选三-9(前三)"
		}, {
			"oddsgno": 271,
			"oddsgname": "组选三-9(中三)"
		}, {
			"oddsgno": 272,
			"oddsgname": "组选三-9(后三)"
		}, {
			"oddsgno": 273,
			"oddsgname": "组三全包(前三)"
		},
		{
			"oddsgno": 274,
			"oddsgname": "组三全包(中三)"
		}, {
			"oddsgno": 275,
			"oddsgname": "组三全包(后三)"
		}, {
			"oddsgno": 276,
			"oddsgname": "组选六-4(前三)"
		}, {
			"oddsgno": 277,
			"oddsgname": "组选六-4(中三)"
		}, {
			"oddsgno": 278,
			"oddsgname": "组选六-4(后三)"
		}, {
			"oddsgno": 279,
			"oddsgname": "组选六-5(前三)"
		}, {
			"oddsgno": 280,
			"oddsgname": "组选六-5(中三)"
		}, {
			"oddsgno": 281,
			"oddsgname": "组选六-5(后三)"
		},
		{
			"oddsgno": 282,
			"oddsgname": "组选六-6(前三)"
		}, {
			"oddsgno": 283,
			"oddsgname": "组选六-6(中三)"
		}, {
			"oddsgno": 284,
			"oddsgname": "组选六-6(后三)"
		}, {
			"oddsgno": 285,
			"oddsgname": "组选六-7(前三)"
		}, {
			"oddsgno": 286,
			"oddsgname": "组选六-7(中三)"
		}, {
			"oddsgno": 287,
			"oddsgname": "组选六-7(后三)"
		}, {
			"oddsgno": 288,
			"oddsgname": "组选六-8(前三)"
		}, {
			"oddsgno": 289,
			"oddsgname": "组选六-8(中三)"
		},
		{
			"oddsgno": 290,
			"oddsgname": "组选六-8(后三)"
		}, {
			"oddsgno": 291,
			"oddsgname": "复式组合(前三)"
		}, {
			"oddsgno": 292,
			"oddsgname": "复式组合(中三)"
		}, {
			"oddsgno": 293,
			"oddsgname": "复式组合(后三)"
		}, {
			"oddsgno": 294,
			"oddsgname": "百拾和数(前三)"
		}, {
			"oddsgno": 295,
			"oddsgname": "百拾和数(中三)"
		}, {
			"oddsgno": 296,
			"oddsgname": "百拾和数(后三)"
		}, {
			"oddsgno": 297,
			"oddsgname": "百个和数(前三)"
		},
		{
			"oddsgno": 298,
			"oddsgname": "百个和数(中三)"
		}, {
			"oddsgno": 299,
			"oddsgname": "百个和数(后三)"
		}, {
			"oddsgno": 300,
			"oddsgname": "拾个和数(前三)"
		}, {
			"oddsgno": 301,
			"oddsgname": "拾个和数(中三)"
		}, {
			"oddsgno": 302,
			"oddsgname": "拾个和数(后三)"
		}, {
			"oddsgno": 303,
			"oddsgname": "百拾和数尾数(前三)"
		}, {
			"oddsgno": 304,
			"oddsgname": "百拾和数尾数(中三)"
		},
		{
			"oddsgno": 305,
			"oddsgname": "百拾和数尾数(后三)"
		}, {
			"oddsgno": 306,
			"oddsgname": "百个和数尾数(前三)"
		}, {
			"oddsgno": 307,
			"oddsgname": "百个和数尾数(中三)"
		}, {
			"oddsgno": 308,
			"oddsgname": "百个和数尾数(后三)"
		}, {
			"oddsgno": 309,
			"oddsgname": "拾个和数尾数(前三)"
		}, {
			"oddsgno": 310,
			"oddsgname": "拾个和数尾数(中三)"
		}, {
			"oddsgno": 311,
			"oddsgname": "拾个和数尾数(后三)"
		}, {
			"oddsgno": 312,
			"oddsgname": "百拾个和数(前三)"
		}, {
			"oddsgno": 313,
			"oddsgname": "百拾个和数(中三)"
		}, {
			"oddsgno": 314,
			"oddsgname": "百拾个和数(后三)"
		}, {
			"oddsgno": 315,
			"oddsgname": "百拾个和数尾数(前三)"
		}, {
			"oddsgno": 316,
			"oddsgname": "百拾个和数尾数(中三)"
		}, {
			"oddsgno": 317,
			"oddsgname": "百拾个和数尾数(后三)"
		},
		{
			"oddsgno": 318,
			"oddsgname": "百拾个和数尾数大小(前三)"
		}, {
			"oddsgno": 319,
			"oddsgname": "百拾个和数尾数大小(中三)"
		}, {
			"oddsgno": 320,
			"oddsgname": "百拾个和数尾数大小(后三)"
		}, {
			"oddsgno": 321,
			"oddsgname": "百拾个和数尾数质合(前三)"
		}, {
			"oddsgno": 322,
			"oddsgname": "百拾个和数尾数质合(中三)"
		}, {
			"oddsgno": 323,
			"oddsgname": "百拾个和数尾数质合(后三)"
		}, {
			"oddsgno": 324,
			"oddsgname": "一字过关(前三)"
		}, {
			"oddsgno": 325,
			"oddsgname": "一字过关(中三)"
		}, {
			"oddsgno": 326,
			"oddsgname": "一字过关(后三)"
		}, {
			"oddsgno": 327,
			"oddsgname": "跨度(前三)"
		}, {
			"oddsgno": 328,
			"oddsgname": "跨度(中三)"
		}, {
			"oddsgno": 329,
			"oddsgname": "跨度(后三)"
		}, {
			"oddsgno": 330,
			"oddsgname": "豹子(前三)"
		},
		{
			"oddsgno": 331,
			"oddsgname": "豹子(中三)"
		}, {
			"oddsgno": 332,
			"oddsgname": "豹子(后三)"
		}, {
			"oddsgno": 333,
			"oddsgname": "顺子(前三)"
		}, {
			"oddsgno": 334,
			"oddsgname": "顺子(中三)"
		}, {
			"oddsgno": 335,
			"oddsgname": "顺子(后三)"
		}, {
			"oddsgno": 336,
			"oddsgname": "对子(前三)"
		}, {
			"oddsgno": 337,
			"oddsgname": "对子(中三)"
		}, {
			"oddsgno": 338,
			"oddsgname": "对子(后三)"
		}, {
			"oddsgno": 339,
			"oddsgname": "半顺(前三)"
		},
		{
			"oddsgno": 340,
			"oddsgname": "半顺(中三)"
		}, {
			"oddsgno": 341,
			"oddsgname": "半顺(后三)"
		}, {
			"oddsgno": 342,
			"oddsgname": "杂六(前三)"
		}, {
			"oddsgno": 343,
			"oddsgname": "杂六(中三)"
		}, {
			"oddsgno": 344,
			"oddsgname": "杂六(后三)"
		}, {
			"oddsgno": 345,
			"oddsgname": "总和单双"
		}, {
			"oddsgno": 346,
			"oddsgname": "总和大小"
		}, {
			"oddsgno": 347,
			"oddsgname": "龙虎和"
		}, {
			"oddsgno": 348,
			"oddsgname": "1,2球和数单双"
		},
		{
			"oddsgno": 349,
			"oddsgname": "1,3球和数单双"
		}, {
			"oddsgno": 350,
			"oddsgname": "1,4球和数单双"
		}, {
			"oddsgno": 351,
			"oddsgname": "1,5球和数单双"
		}, {
			"oddsgno": 352,
			"oddsgname": "2,3球和数单双"
		}, {
			"oddsgno": 353,
			"oddsgname": "2,4球和数单双"
		}, {
			"oddsgno": 354,
			"oddsgname": "2,5球和数单双"
		}, {
			"oddsgno": 355,
			"oddsgname": "3,4球和数单双"
		}, {
			"oddsgno": 356,
			"oddsgname": "3,5球和数单双"
		},
		{
			"oddsgno": 357,
			"oddsgname": "4,5球和数单双"
		}, {
			"oddsgno": 358,
			"oddsgname": "牛牛"
		}, {
			"oddsgno": 359,
			"oddsgname": "牛单双"
		}, {
			"oddsgno": 360,
			"oddsgname": "牛大小"
		}, {
			"oddsgno": 361,
			"oddsgname": "牛质合"
		}, {
			"oddsgno": 362,
			"oddsgname": "梭哈"
		}, {
			"oddsgno": 368,
			"oddsgname": "1,2球和数尾数大小"
		}, {
			"oddsgno": 369,
			"oddsgname": "1,3球和数尾数大小"
		}, {
			"oddsgno": 370,
			"oddsgname": "1,4球和数尾数大小"
		},
		{
			"oddsgno": 371,
			"oddsgname": "1,5球和数尾数大小"
		}, {
			"oddsgno": 372,
			"oddsgname": "2,3球和数尾数大小"
		}, {
			"oddsgno": 373,
			"oddsgname": "2,4球和数尾数大小"
		}, {
			"oddsgno": 374,
			"oddsgname": "2,5球和数尾数大小"
		}, {
			"oddsgno": 375,
			"oddsgname": "3,4球和数尾数大小"
		}, {
			"oddsgno": 376,
			"oddsgname": "3,5球和数尾数大小"
		}, {
			"oddsgno": 377,
			"oddsgname": "4,5球和数尾数大小"
		},
		{
			"oddsgno": 401,
			"oddsgname": "第一球"
		}, {
			"oddsgno": 402,
			"oddsgname": "第二球"
		}, {
			"oddsgno": 403,
			"oddsgname": "第三球"
		}, {
			"oddsgno": 404,
			"oddsgname": "第四球"
		}, {
			"oddsgno": 405,
			"oddsgname": "第五球"
		}, {
			"oddsgno": 406,
			"oddsgname": "第六球"
		}, {
			"oddsgno": 407,
			"oddsgname": "第七球"
		}, {
			"oddsgno": 408,
			"oddsgname": "第八球"
		}, {
			"oddsgno": 409,
			"oddsgname": "第1球单双"
		}, {
			"oddsgno": 410,
			"oddsgname": "第2球单双"
		},
		{
			"oddsgno": 411,
			"oddsgname": "第3球单双"
		}, {
			"oddsgno": 412,
			"oddsgname": "第4球单双"
		}, {
			"oddsgno": 413,
			"oddsgname": "第5球单双"
		}, {
			"oddsgno": 414,
			"oddsgname": "第6球单双"
		}, {
			"oddsgno": 415,
			"oddsgname": "第7球单双"
		}, {
			"oddsgno": 416,
			"oddsgname": "第8球单双"
		}, {
			"oddsgno": 417,
			"oddsgname": "第1球大小"
		}, {
			"oddsgno": 418,
			"oddsgname": "第2球大小"
		}, {
			"oddsgno": 419,
			"oddsgname": "第3球大小"
		},
		{
			"oddsgno": 420,
			"oddsgname": "第4球大小"
		}, {
			"oddsgno": 421,
			"oddsgname": "第5球大小"
		}, {
			"oddsgno": 422,
			"oddsgname": "第6球大小"
		}, {
			"oddsgno": 423,
			"oddsgname": "第7球大小"
		}, {
			"oddsgno": 424,
			"oddsgname": "第8球大小"
		}, {
			"oddsgno": 425,
			"oddsgname": "第1球合数单双"
		}, {
			"oddsgno": 426,
			"oddsgname": "第2球合数单双"
		}, {
			"oddsgno": 427,
			"oddsgname": "第3球合数单双"
		}, {
			"oddsgno": 428,
			"oddsgname": "第4球合数单双"
		},
		{
			"oddsgno": 429,
			"oddsgname": "第5球合数单双"
		}, {
			"oddsgno": 430,
			"oddsgname": "第6球合数单双"
		}, {
			"oddsgno": 431,
			"oddsgname": "第7球合数单双"
		}, {
			"oddsgno": 432,
			"oddsgname": "第8球合数单双"
		}, {
			"oddsgno": 433,
			"oddsgname": "第1球尾数大小"
		}, {
			"oddsgno": 434,
			"oddsgname": "第2球尾数大小"
		}, {
			"oddsgno": 435,
			"oddsgname": "第3球尾数大小"
		}, {
			"oddsgno": 436,
			"oddsgname": "第4球尾数大小"
		},
		{
			"oddsgno": 437,
			"oddsgname": "第5球尾数大小"
		}, {
			"oddsgno": 438,
			"oddsgname": "第6球尾数大小"
		}, {
			"oddsgno": 439,
			"oddsgname": "第7球尾数大小"
		}, {
			"oddsgno": 440,
			"oddsgname": "第8球尾数大小"
		}, {
			"oddsgno": 441,
			"oddsgname": "第1球方向"
		}, {
			"oddsgno": 442,
			"oddsgname": "第2球方向"
		}, {
			"oddsgno": 443,
			"oddsgname": "第3球方向"
		}, {
			"oddsgno": 444,
			"oddsgname": "第4球方向"
		}, {
			"oddsgno": 445,
			"oddsgname": "第5球方向"
		}, {
			"oddsgno": 446,
			"oddsgname": "第6球方向"
		}, {
			"oddsgno": 447,
			"oddsgname": "第7球方向"
		}, {
			"oddsgno": 448,
			"oddsgname": "第8球方向"
		}, {
			"oddsgno": 449,
			"oddsgname": "第1球中发白"
		}, {
			"oddsgno": 450,
			"oddsgname": "第2球中发白"
		}, {
			"oddsgno": 451,
			"oddsgname": "第3球中发白"
		}, {
			"oddsgno": 452,
			"oddsgname": "第4球中发白"
		}, {
			"oddsgno": 453,
			"oddsgname": "第5球中发白"
		},
		{
			"oddsgno": 454,
			"oddsgname": "第6球中发白"
		}, {
			"oddsgno": 455,
			"oddsgname": "第7球中发白"
		}, {
			"oddsgno": 456,
			"oddsgname": "第8球中发白"
		}, {
			"oddsgno": 457,
			"oddsgname": "总和单双"
		}, {
			"oddsgno": 458,
			"oddsgname": "总和大小"
		}, {
			"oddsgno": 459,
			"oddsgname": "总和尾数大小"
		}, {
			"oddsgno": 460,
			"oddsgname": "龙虎"
		}, {
			"oddsgno": 461,
			"oddsgname": "选一数投"
		}, {
			"oddsgno": 462,
			"oddsgname": "选一红投"
		},
		{
			"oddsgno": 463,
			"oddsgname": "任选二"
		}, {
			"oddsgno": 464,
			"oddsgname": "选二连直"
		}, {
			"oddsgno": 465,
			"oddsgname": "选二连组"
		}, {
			"oddsgno": 466,
			"oddsgname": "任选三"
		}, {
			"oddsgno": 467,
			"oddsgname": "选三前直"
		}, {
			"oddsgno": 468,
			"oddsgname": "选三前组"
		}, {
			"oddsgno": 469,
			"oddsgname": "任选四"
		}, {
			"oddsgno": 470,
			"oddsgname": "任选五"
		}, {
			"oddsgno": 601,
			"oddsgname": "冠军"
		}, {
			"oddsgno": 602,
			"oddsgname": "亚军"
		},
		{
			"oddsgno": 603,
			"oddsgname": "第三名"
		}, {
			"oddsgno": 604,
			"oddsgname": "第四名"
		}, {
			"oddsgno": 605,
			"oddsgname": "第五名"
		}, {
			"oddsgno": 606,
			"oddsgname": "第六名"
		}, {
			"oddsgno": 607,
			"oddsgname": "第七名"
		}, {
			"oddsgno": 608,
			"oddsgname": "第八名"
		}, {
			"oddsgno": 609,
			"oddsgname": "第九名"
		}, {
			"oddsgno": 610,
			"oddsgname": "第十名"
		}, {
			"oddsgno": 611,
			"oddsgname": "冠军单双"
		}, {
			"oddsgno": 612,
			"oddsgname": "亚军单双"
		},
		{
			"oddsgno": 613,
			"oddsgname": "第三名单双"
		}, {
			"oddsgno": 614,
			"oddsgname": "第四名单双"
		}, {
			"oddsgno": 615,
			"oddsgname": "第五名单双"
		}, {
			"oddsgno": 616,
			"oddsgname": "第六名单双"
		}, {
			"oddsgno": 617,
			"oddsgname": "第七名单双"
		}, {
			"oddsgno": 618,
			"oddsgname": "第八名单双"
		}, {
			"oddsgno": 619,
			"oddsgname": "第九名单双"
		}, {
			"oddsgno": 620,
			"oddsgname": "第十名单双"
		}, {
			"oddsgno": 621,
			"oddsgname": "冠军大小"
		}, {
			"oddsgno": 622,
			"oddsgname": "亚军大小"
		}, {
			"oddsgno": 623,
			"oddsgname": "第三名大小"
		}, {
			"oddsgno": 624,
			"oddsgname": "第四名大小"
		}, {
			"oddsgno": 625,
			"oddsgname": "第五名大小"
		}, {
			"oddsgno": 626,
			"oddsgname": "第六名大小"
		}, {
			"oddsgno": 627,
			"oddsgname": "第七名大小"
		}, {
			"oddsgno": 628,
			"oddsgname": "第八名大小"
		}, {
			"oddsgno": 629,
			"oddsgname": "第九名大小"
		},
		{
			"oddsgno": 630,
			"oddsgname": "第十名大小"
		}, {
			"oddsgno": 631,
			"oddsgname": "冠军龙虎"
		}, {
			"oddsgno": 632,
			"oddsgname": "亚军龙虎"
		}, {
			"oddsgno": 633,
			"oddsgname": "第三名龙虎"
		}, {
			"oddsgno": 634,
			"oddsgname": "第四名龙虎"
		}, {
			"oddsgno": 635,
			"oddsgname": "第五名龙虎"
		}, {
			"oddsgno": 636,
			"oddsgname": "冠亚和单双"
		}, {
			"oddsgno": 637,
			"oddsgname": "冠亚和大小"
		}, {
			"oddsgno": 638,
			"oddsgname": "冠亚和"
		},
		{
			"oddsgno": 701,
			"oddsgname": "大小"
		}, {
			"oddsgno": 702,
			"oddsgname": "三军"
		}, {
			"oddsgno": 703,
			"oddsgname": "围骰"
		}, {
			"oddsgno": 704,
			"oddsgname": "全骰"
		}, {
			"oddsgno": 705,
			"oddsgname": "点数"
		}, {
			"oddsgno": 706,
			"oddsgname": "长牌"
		}, {
			"oddsgno": 707,
			"oddsgname": "短牌"
		}, {
			"oddsgno": 801,
			"oddsgname": "正码"
		}, {
			"oddsgno": 802,
			"oddsgname": "总和大小"
		}, {
			"oddsgno": 803,
			"oddsgname": "总和单双"
		}, {
			"oddsgno": 804,
			"oddsgname": "总和810"
		}, {
			"oddsgno": 805,
			"oddsgname": "总和过关"
		}, {
			"oddsgno": 806,
			"oddsgname": "前后和"
		}, {
			"oddsgno": 807,
			"oddsgname": "单双和"
		}, {
			"oddsgno": 808,
			"oddsgname": "五行"
		}
	]
}